name: 'Publish application'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '6.0.x'

        # Generate the website
        - name: Publish
          run: dotnet publish myapp.csproj --configuration Release

        # Publish the website
        - name: GitHub Pages action
          if: ${{ github.ref == 'refs/heads/master' }} # Publish only when the push is on master
          uses: peaceiris/actions-gh-pages@v3.6.1
          with:
            github_token: ${{ secrets.PUBLISH_TOKEN }}
            publish_branch: gh-pages
            publish_dir: bin/Release/net6.0/publish/wwwroot
            allow_empty_commit: false
            keep_files: false
            force_orphan: true
